// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:3.1.0.0
//      SpecFlow Generator Version:3.1.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace MarsQA_1.Feature
{
    using TechTalk.SpecFlow;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.1.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("ManageRequest")]
    public partial class ManageRequestFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
        private string[] _featureTags = ((string[])(null));
        
#line 1 "ManageRequest.feature"
#line hidden
        
        [NUnit.Framework.OneTimeSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "ManageRequest", "As a Seller\r\nI want the feature to see a ReceivedRequests to the Profile\r\nSo that" +
                    "\r\nThe people seeking for specific ReceivedRequests can look into my details.\r\n\r\n" +
                    "Acceptance Criteria\r\nSeller is able to see the ReceivedRequests", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.OneTimeTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void TestTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<NUnit.Framework.TestContext>(NUnit.Framework.TestContext.CurrentContext);
        }
        
        public virtual void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Test to view the list of ReceivedRequets records sucessfully")]
        [NUnit.Framework.CategoryAttribute("mytag")]
        public virtual void TestToViewTheListOfReceivedRequetsRecordsSucessfully()
        {
            string[] tagsOfScenario = new string[] {
                    "mytag"};
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Test to view the list of ReceivedRequets records sucessfully", null, new string[] {
                        "mytag"});
#line 12
this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
                TechTalk.SpecFlow.Table table2 = new TechTalk.SpecFlow.Table(new string[] {
                            "Category",
                            "Title"});
                table2.AddRow(new string[] {
                            "Graphics & Design",
                            "Postman"});
                table2.AddRow(new string[] {
                            "Business",
                            "Swagger UI"});
                table2.AddRow(new string[] {
                            "Graphics & Design",
                            "Postman"});
                table2.AddRow(new string[] {
                            "Graphics & Design",
                            "Automation"});
                table2.AddRow(new string[] {
                            "Business",
                            "Manual testing"});
#line 13
 testRunner.Given("the user has received the following requests", ((string)(null)), table2, "Given ");
#line hidden
#line 20
 testRunner.When("the user clicks \"Received Requests\" link under Manage Requests tab", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
                TechTalk.SpecFlow.Table table3 = new TechTalk.SpecFlow.Table(new string[] {
                            "Category",
                            "Title",
                            "Message",
                            "Sender",
                            "Status",
                            "Type",
                            "Date"});
                table3.AddRow(new string[] {
                            "Graphics & Design",
                            "Postman",
                            "Hi",
                            "supriya",
                            "Completed",
                            "Exchange",
                            "14th Sep, 2021"});
                table3.AddRow(new string[] {
                            "Business",
                            "Swagger UI",
                            "Hi",
                            "priya",
                            "Accepted",
                            "Exchange",
                            "13th Sep, 2021"});
                table3.AddRow(new string[] {
                            "Graphics & Design",
                            "Postman",
                            "Hi",
                            "priya",
                            "Accepted",
                            "Exchange",
                            "13th Sep, 2021"});
                table3.AddRow(new string[] {
                            "Graphics & Design",
                            "Automation",
                            "Hi",
                            "priya",
                            "Declined",
                            "Exchange",
                            "13th Sep, 2021"});
                table3.AddRow(new string[] {
                            "Business",
                            "Manual testing",
                            "Hi this Supriya",
                            "priya",
                            "Declined",
                            "Exchange",
                            "13th Sep, 2021"});
#line 21
 testRunner.Then("the Received Requests list page is displayed with the following data", ((string)(null)), table3, "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
